kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: aiops-cluster

nodes:
  - role: control-plane
    labels:
      node-role: control-plane

  - role: worker
    labels:
      node-role: worker

  - role: worker
    labels:
      node-role: worker