apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-nginx
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/baroneleo/AIOps-cluster.git
    targetRevision: main
    path: gitops/apps/nginx

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true